version: '3'

services:
  # start microblog app
  # build a microblog image at . dir
  microblog:
    build: .
    # image: microblog
    container_name: microblog
    ports:
    - "5000:5000"
    env_file:
    - .env_online
    links:
    - mysqldb
    - elasticsearch
  # start elasticsearch service
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
  # start mysql service
  # map a 33060 port for Navicat connect 
  # set mysql root password and host allow microblog service can connect from 172.17.0.0/24
  # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker-persisting-data-configuration
  mysqldb:
    image: mysql/mysql-server:5.7
    container_name: mysqldb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Xyjrgss15
      - MYSQL_ROOT_HOST=172.%.%.%
      - MYSQL_DATABASE=microblog
      # - MYSQL_DATABASE=postfix
      # - MYSQL_USER=postfix
      # - MYSQL_PASSWORD=asdf:LKJ
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  esdata:
    driver: local
  mysqldata:
    driver: local