"""followers

Revision ID: 771bf2bf3ffc
Revises: f5c838f7f66f
Create Date: 2018-07-31 17:22:22.121871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771bf2bf3ffc'
down_revision = 'f5c838f7f66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
